### PR TITLE
Uberdemand Update

### PR DESCRIPTION
**Pull request by javelinanddart**

### CODE REVIEW

**Comment by javelinanddart** [comment]
You could also take it a step further and add architecture specific defaults, that's up to you though

**Comment by Cl3Kener** [comment]
Thanks Paul!  I won't merge this to master yet so I'll close the pull request, but you can see I've added these changes to my test branch https://github.com/Cl3Kener/UBER-L/commits/test.  I probably should have done this and even done the arch specific idea that you mentioned but I honestly didn't think any other kernel would care about uberdemand.  I guess I don't always think or dream big enough....

**Comment by javelinanddart** [comment]
I think you used the calculation 75% of Max Freq
In that case MSM8960/MSM8660/APQ8064 at 1.5GHz (Mako, Hercules) would be 1134000
In the case of APQ8064T (M7/T6/Snapdragon 600) at 1.7GHz would be 1296000
In the case of APQ8064T (S4/Snapdragon 600 AB) at 1.9GHz would be 1458000
Any Misc 8960/8660 which are at 1.2GHz (Fireball, Exhilarate) would be about 918000
You already have the calculations for 8974

**Comment by javelinanddart** [comment]
I haven't really tried this Gov, been using Badass (For which you're missing 2 phase hooks and GPU Control Stuff)
Badass GPU Control
https://github.com/CandyDevices/kernel_samsung_jf/commit/137ac4b9c2ca347790865b54026abdd91a3bba87
Badass Phase Hooks
https://github.com/CandyDevices/kernel_samsung_jf/commit/cfa45a2d89112f07974546b564c06e9d8c84f98c
Tune GPU Control Part 1
https://github.com/CandyDevices/kernel_samsung_jf/commit/66a81cbfce85ee35cd96b3e55116fa61caa38cd9
Tune GPU Control Part 2
https://github.com/CandyDevices/kernel_samsung_jf/commit/27b8f674bec281b242eac6a262993afdee566318
Tuning 2 and 3 Phase for 1.9GHz CPU
https://github.com/CandyDevices/kernel_samsung_jf/commit/4f3aaa79ab60057194a8f5afa5bba8c253c7be02
Sync with Upstream Ondemand
https://github.com/CandyDevices/kernel_samsung_jf/commit/3c5dc7317eedda6a07c38e2cabdc2bfac6bd79de

**Comment by javelinanddart** [comment]
Those are all for JF
I'll give uberdemand a shot this weekend after tuning it

**Comment by Cl3Kener** [comment]
I didn't realize there were gpu hooks and such in the original badass governor.  I honestly don't remember where I found the version I currently have but I don't think it had these GPU tunings.  I do have the hooks for badass but I was lazy and clumped them together https://github.com/Cl3Kener/UBER-L/commit/472a0cfe7f6f1d9c38faf601f1d5af4264f2683b just because I figured if you're going to use badass you might as well use both. I'll have to give the GPU stuff a try! Thanks for the heads up!

**Comment by javelinanddart** [comment]
No problem.
You should be using the config macro in the board file hooks, just fyi, You could hardcode them but that would defeat the purpose of having the config option entirely.
I went through showp1984's stuff when he first created badass to see what he did, the hooks and all and added them from there. You'll want to tune those thresholds for GPU Control though
    - The Semi Busy Threshold is about 95-100% of the Max GPU Clock
    - The Semi Busy Clear Threshold is about 66% of the Max GPU Clock
    - The Busy Threshold is about about 263-266% of the Max GPU Clock
    - The Busy Clear Threshold is about 1s about 188% of the Max GPU Clock
(The more accurate you are the better it will be)
You'll want to add the GPU Control, tune it, and pick the upstream commit in, I've found it really helps battery life and responsiveness.

**Comment by javelinanddart** [comment]
At least that's what my testing has shown me

**Comment by javelinanddart** [comment]
@Cl3Kener Added Those Arch Specific Defaults
https://github.com/VilleEvitaCake/android_kernel_htc_msm8960/commit/7bd987d8c004ac56525b87e1e46d122d0f69b475
I left 8660 at the default for 1.2GHz because that's the most common one
Default regardless is the one for 1 GHz, might need some tweaking

**Comment by javelinanddart** [comment]
https://github.com/VilleEvitaCake/android_kernel_htc_msm8960/commit/686f53f1805071ed18a7ec8e08fa06c4d5a3a1f5 Fixed a derp

**Pull request closed without merging**
